package View;

import Controller.LoginController;
import Model.DAO.Banco;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

public class Login extends javax.swing.JFrame {

    private final LoginController controller;

    public Login() {
        initComponents();
       
        controller = new LoginController(this);
        Banco.inicia();//inicia o banco de dados
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButEntrar = new javax.swing.JButton();
        TextSenha = new javax.swing.JPasswordField();
        Senha = new javax.swing.JLabel();
        TextUsuario = new javax.swing.JTextField();
        Usuário = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        FundoLogin = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButEntrar.setBackground(new java.awt.Color(153, 153, 153));
        ButEntrar.setForeground(new java.awt.Color(255, 255, 255));
        ButEntrar.setText("Entrar");
        ButEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(ButEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 620, 140, 40));

        TextSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(TextSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 180, 40));

        Senha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Senha.setForeground(new java.awt.Color(255, 255, 255));
        Senha.setText("Senha");
        getContentPane().add(Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, -1, -1));
        getContentPane().add(TextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 180, 40));

        Usuário.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Usuário.setForeground(new java.awt.Color(255, 255, 255));
        Usuário.setText("Usuário");
        getContentPane().add(Usuário, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, -1));

        Login.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setText("Login");
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));

        FundoLogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cleyt\\OneDrive\\Documentos\\NetBeansProjects\\Java\\BarberShop\\src\\main\\java\\View\\imagens\\painel-login.png")); // NOI18N
        getContentPane().add(FundoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 660, -1));

        Fundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cleyt\\OneDrive\\Documentos\\NetBeansProjects\\Java\\BarberShop\\src\\main\\java\\View\\imagens\\Logo.jpg")); // NOI18N
        getContentPane().add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 798, 1138));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextSenhaActionPerformed

    private void ButEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButEntrarActionPerformed
        // TODO add your handling code here:
        this.controller.entrarNoSistema();
    }//GEN-LAST:event_ButEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButEntrar;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel FundoLogin;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel Senha;
    private javax.swing.JPasswordField TextSenha;
    private javax.swing.JTextField TextUsuario;
    private javax.swing.JLabel Usuário;
    // End of variables declaration//GEN-END:variables
  public void exibeMensagem(String mensagem) {
       JOptionPane.showMessageDialog(null,mensagem);
    }

    public JPasswordField getTextSenha() {
        return TextSenha;
    }

    public void setTextSenha(JPasswordField TextSenha) {
        this.TextSenha = TextSenha;
    }

    public JTextField getTextUsuario() {
        return TextUsuario;
    }

    public void setTextUsuario(JTextField TextUsuario) {
        this.TextUsuario = TextUsuario;
    }

 
    
}







